---
title: "Abstract"
---

We propose to develop plans for a [NASA field campaign](http://cce.nasa.gov/cgi-bin/cce/cce_profile.pl?project_group_id=3530) incorporating hyperspectral, lidar, and field observations across the Greater Cape Floristic Region (GCFR) of southwestern Africa. The GCFR includes several formally defined biomes, but the majority of the area is made up of the fire-prone Fynbos shrubland and arid Succulent Karoo biomes, which form the core of two Global Biodiversity Hotspots circumscribed by the region. The GCFR also includes portions of the Forest, Nama-Karoo, Thicket and Grassland biomes. Off the coast, South Africa’s oceans include both temperate and tropical marine biomes dominated by two ocean currents: the cold Benguela Current and the warm Agulhas Current. Upwelling conditions off the west and south-west coasts contribute to a high net productivity (60-70 times greater than the averages of areas such as California and Peru). At the interface of land and sea are extensive freshwater ecosystems that match the GCFR in levels of species endemism and are a critical source of water in a water scarce nation. The terrestrial ecosystems contain 11,500 species of flowering plants in over 1000 genera and 178 families, with new species being discovered every year. Of these species, 78% are endemic, an extraordinarily high number for a continental area making the GCFR one of the world’s hottest biodiversity hotspots with species diversity rivaling that of mega-diverse tropical rainforests in an extremely compact area approximately 300x700km. The marine systems also have some of the highest levels of marine endemism globally; approximately 3,500 (28% of recorded marine species) are endemic. The GCFR also contains one of the highest proportions of species of global conservation concern; extinction risk studies indicate that GCFR species are among the most vulnerable to climate change over the next 50 years. While 23% of South Africa’s coastlines are environmentally protected, 47% of the coastal and marine environments have been identified as environmentally threatened. The Cape region has been a focal area for the study of evolution since Darwin rounded the Cape on the Beagle and ecology since Hutchinson first started studying limology and ecology here in the1920s. This historical attention has led to the collection of more in situ data on the biotic and abiotic dimensions than perhaps anyother biodiverse region globally. Our plan centers around the collection of new hyperspectral imagery from AVIRIS-NG, PRISM, and HyTES spectrometers combined with the LVIS laser altimeter. These data will be collected at finest possible spatial resolution (~30 cm) over a set of ‘focal’ areas identified to span environmental and species composition gradients and at lower spatial resolution (~10m) across much of the GCFR and nearby aquatic and marine ecosystems. These data will then be combined with existing and new observations of the spatial distribution of community composition and functional traits to enable high resolution mapping of functional traits (including leaf properties and foliar chemistry) as well as three-dimensional canopy structure to improve our understanding of the spatial distribution of ecosystems and biomes as well as species abundance and their associated traits. Given the wealth of independent in situ data available that can be brought to bear, the GCFR is an ideal system to fully evaluate the capabilities of remote-sensing technology to characterize biodiversity patterns across diverse landscapes in a relatively compact geographic area. In combination with the rich historical data and well-developed ecological understanding in this region, these new observations will enable detailed exploration into the drivers and mechanisms of change across the region including the feedbacks from changing biodiversity to regional climate, disturbance, post-fire recovery, freshwater provisioning, and other ecosystem services. 

# Project Team

* [Adam M. Wilson, PI (University at Buffalo)](http://adamwilson.us)
* [John Silander, Co-I (University of Connecticut)](http://hydrodictyon.eeb.uconn.edu/people/silander/)
* [Cory Merow (Yale University)](https://cmerow.github.io)
* Henry Frye (University of Connecticut)